{% set name = "pyregion" %}
{% set version = "2.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a8ac5f764b53ec332f6bc43f6f2193ca13e8b7d5a3fb2e20ced6b2ea42a9d094" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1001
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy        # [not (py36 and win)]
    - numpy         # [py36 and win]
    - cython
  run:
    - python
    - pyparsing >=2.0.0
    - astropy
    - {{ pin_compatible('numpy') }}   # [not (py36 and win)]
    - {{ pin_compatible('numpy') }}   # [py36 and win]

test:
  imports:
    - pyregion

about:
  home: https://github.com/astropy/pyregion
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python parser for ds9 and ciao region files
  description: |
    pyregion is a python module to parse ds9 region files. It also supports
    ciao region files. Please note that the main emphasis of the package is to
    read in the regions files generated by ds9 itself. It reads most of the
    region files created by ds9. However, it may fail to read some of the
    user-created (or created by other programs) region files, even if they can
    be successfully read by ds9.
  doc_url: https://pyregion.readthedocs.io
  dev_url: https://github.com/astropy/pyregion

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
