{% set name = "pyregion" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8498711421173239689de523bb465245f5551a18a181cb4956d87f9c7464925

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - numpy        # [not (py==36 and win)]
    - numpy         # [py==36 and win]
    - cython
  run:
    - python
    - pyparsing >=2.0.0
    - astropy
    - {{ pin_compatible('numpy') }}   # [not (py==36 and win)]
    - {{ pin_compatible('numpy') }}   # [py==36 and win]

test:
  imports:
    - pyregion

about:
  home: https://github.com/astropy/pyregion
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python parser for ds9 and ciao region files
  description: |
    pyregion is a python module to parse ds9 region files. It also supports
    ciao region files. Please note that the main emphasis of the package is to
    read in the regions files generated by ds9 itself. It reads most of the
    region files created by ds9. However, it may fail to read some of the
    user-created (or created by other programs) region files, even if they can
    be successfully read by ds9.
  doc_url: https://pyregion.readthedocs.io
  dev_url: https://github.com/astropy/pyregion

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
